version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongodb-data: